version: '3.4'

services:
  vshop:
    image: nodeshop
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5020:5020
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
